### ISSUE TITLE
Disappeared service endpoints

### ISSUE THREAD

**Issue by paivin-dn** [pomerium/ingress-controller#1015]
## What happened?
I tried to set up proxying from the k8s cluster to external service using Pomerium ingress controller + service + endpoint.
My manifests look like:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysvc
  labels:
    app: mysvc
spec:
  selector:
    app: mysvc
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
```
```yaml
apiVersion: v1
kind: Endpoints
metadata:
  name: mysvc
  labels:
    app: mysvc
subsets:
  - addresses:
      - ip: 10.101.10.5
    ports:
      - name: web
        port: 80
        protocol: TCP

```
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tech-docs
  annotations:
    ingress.pomerium.io/policy: |
      - allow:
          or:
            - domain:
                is: example.com
spec:
  ingressClassName: pomerium
  rules:
    - host: myhost.example.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: mysvc
                port:
                  number: 80

```
After deploying it works, but several hours later I see that the IP address in the Endpoint was deleted.

## What did you expect to happen?
The IP in the Endpoint should exist.

## How'd it happen?

1. Ran `x`
2. Clicked `y`
3. Saw error `z`

## What's your environment like?

- cloud k8s in digitlaocen, pomerium deployed 0.25.0

## What's your config.yaml?

```config.yaml
apiVersion: ingress.pomerium.io/v1
kind: Pomerium
metadata:
  name: global
spec:
  secrets: "pomerium/bootstrap"
  authenticate:
    url: "https://myayth.example.com"
  storage:
    postgres:
      secret: "pomerium/storage"
  identityProvider:
    provider: auth0
    secret: pomerium/provider"
    url: "auth0_url"
  certificates:
    - "pomerium/cert"

```

## What did you see in the logs?

```logs
"level":"warn","time":"2024-07-18T20:39:37Z","msg":"stapling OCSP","service":"autocert","error":"unable to write OCSP staple file for [*.example.com example.com]: mkdir /.local: read-only file system"
```
