### ISSUE TITLE
Invalid ClusterRole definition leads to error during installation and creation of the bootstrap secret

### ISSUE THREAD

**Issue by huguesalary** [pomerium/ingress-controller#1104]
## What happened?

An error while installing Pomerium with `kubectl apply -k github.com/pomerium/ingress-controller/config/default\?ref=v0.27.2`

Specifically, the Pod created by the `job/pomerium-gen-secrets`, fails with the following error:

```
Error: check existing secret: secrets "bootstrap" is forbidden: User "system:serviceaccount:pomerium:pomerium-gen-secrets" cannot get resource "secrets" in API group "" in the namespace "pomerium"
2025/02/20 01:14:49 check existing secret: secrets "bootstrap" is forbidden: User "system:serviceaccount:pomerium:pomerium-gen-secrets" cannot get resource "secrets" in API group "" in the namespace "pomerium"
```

## What's the issue?

After investigating, it appears the issue is with the `clusterrole/pomerium-gen-secrets` definition, which is:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pomerium
  name: pomerium-gen-secrets
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
```

The `verbs:` section is missing `- get`.

Since the process in the `job/pomerium-gen-secrets` is trying to list secrets, the proper definition should be:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pomerium
  name: pomerium-gen-secrets
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get        # <-------- missing get added here
```
