### ISSUE TITLE
Mixed protocol is not supported

### ISSUE THREAD

**Issue by hamzabouissi** [pomerium/ingress-controller#1142]
## What happened?
I just deployed the ingress controller as usual, and ran into the following problem:
`Warning  SyncLoadBalancerFailed  2m36s (x14 over 42m)  service-controller  Error syncing load balancer: failed to ensure load balancer: mixed protocol is not supported for LoadBalancer`

## What did you expect to happen?
Deploying a loadbalancer the same as the old version `v0.27.2` did.

## How'd it happen?
1. spin up an eks cluster with v1.30 version
2. install pomerium-ingress 

## What's your environment like?

- Pomerium version v0.29.2

## What's your config.yaml?
the default

## What did you see in the logs?
logs from  pomerium-proxy svc:
 
`Warning  SyncLoadBalancerFailed  2m36s (x14 over 42m)  service-controller  Error syncing load balancer: failed to ensure load balancer: mixed protocol is not supported for LoadBalancer`

**Comment by dstarcev** [comment]
The `service.beta.kubernetes.io/aws-load-balancer-enable-tcp-udp-listener` annotation for `pomerium-proxy` service solved the problem for me.

The complete set of annotations in my case:

```yaml
external-dns.alpha.kubernetes.io/hostname: auth.your-domain.com
service.beta.kubernetes.io/aws-load-balancer-enable-tcp-udp-listener: 'true' # this helped
service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
service.beta.kubernetes.io/aws-load-balancer-type: external
```
