### ISSUE TITLE
Policy definition in a separate Kubernetes resource

### ISSUE THREAD

**Issue by romainmeunier** [pomerium/ingress-controller#133]
**Is your feature request related to a problem? Please describe.**

 We define routes and policies in the same object ( k8s ingress).

- It doesn't allow RBAC model so a user who defines the route in the Ingress also defines the policy 
- It doesn't allow reusable or cluster wide policies 

**Describe the solution you'd like**
I see two solutions here :

- Using a CustomResource :

```
apiVersion: pomerium.io/v1
kind: globalPolicy
metadata:
  name: myglobalpolicy
spec:
    - allow:
       or:
         - domain:
                is: mydomain.com
```

``` 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.pomerium.io/globalPolicy: myglobalpolicy
spec: 
...

```

- Using a configmap/secret reference.

**Describe alternatives you've considered**

As today, we achieve this by adding annotations in the ingress during admission.
This alternative induces a drawback : The policies are defined only during admission 

**Explain any additional use-cases**
**Additional context**

It may be interesting to use this to define default and global policies
