### ISSUE TITLE
Policy order is not respected with different Ingresses having different Pomerium annotations

### ISSUE THREAD

**Issue by sherifkayad** [pomerium/ingress-controller#135]
## What happened?
Ingress Controller in Operator Mode and two Ingress objects with two different policies for the same domain:
- One is more specific and only allowing users belonging to certain groups (`Team X` or `Team Y`) for a regex path (`/.*/admin`)
- Two is less specific and allowing all authenticated users for the rest of the paths

Users that don't belong to any allowed group defined on Ingress one are authorized by Pomerium! .. So it seems like Pomerium is applying the less specific policy first and not the more specific!

For example hitting `/page1/admin` with a user who's neither part of Team X nor Team Y results in a success while it should have resulted in a 403

## What did you expect to happen?
- ONLY users who belong to Team X or Team Y should be authorized
- Policies should be executed in order e.g. by the chronological order of the Ingress name

**Note:** That was already the behavior of the deprecated Operator .. The policy was constructed by scanning the annotations on the ingresses according to their names.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): Pomerium core `0.16.2` Pomerium Ingress `0.16.1`
- Server Operating System/Architecture/Cloud: AWS EKS with Helm

## Additional context

The Ingress definitions are as follows:
```yaml
## Ingress one
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 0-secure-ingress
  labels:
    app: base
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://forwardauth.mydomain.com/verify?uri=https://$host$request_uri"
    nginx.ingress.kubernetes.io/auth-signin: "https://forwardauth.mydomain.com/?uri=https://$host$request_uri"
    nginx.ingress.kubernetes.io/use-regex: "true"
    ingress.pomerium.io/path_regex: "true"
    ingress.pomerium.io/allowed_idp_claims: '{"groups": ["Team X", "Team Y"]}'
spec:
  ingressClassName: nginx
  rules:
  - host: demo.mydomain.com
    http:
      paths:
      - path: /.*/admin
        pathType: ImplementationSpecific
        backend:
          service:
            name: demo-project
            port:
              number: 8080
---
---
## Ingress two
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 1-secure-ingress
  labels:
    app: base
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: "https://forwardauth.mydomain.com/?uri=https://$host$request_uri"
    nginx.ingress.kubernetes.io/auth-url: "https://forwardauth.mydomain.com/verify?uri=https://$host$request_uri"
    ingress.pomerium.io/allow_any_authenticated_user: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: demo.mydomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-project
            port:
              number: 8080
```

Worth to mention that putting the policies directly in the Pomerium Routes Config makes things work as expected .. So that's definitely an order / setting the right policy issue with the Ingress Controller.

For the sake of completeness, something like that works like a charm:
```yaml
config:
  routes:
  - from: https://demo.mydomain.com
    to: http://demo-project.namespace:8080
    regex: /.*/admin
    allowed_idp_claims:
      groups:
      - Team X
      - Team Y
  - from: https://demo.mydomain.com
    to: http://demo-project.namespace:8080
    prefix: /
    allow_any_authenticated_user: true
```

**Comment by sherifkayad** [comment]
**Update:**
Using a Path Prefix instead of a Regex for the more specific policy works as expected and unauthorized users are denied access.
```yaml
## Ingress one
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 0-secure-ingress
  labels:
    app: base
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://forwardauth.mydomain.com/verify?uri=https://$host$request_uri"
    nginx.ingress.kubernetes.io/auth-signin: "https://forwardauth.mydomain.com/?uri=https://$host$request_uri"
    ingress.pomerium.io/allowed_idp_claims: '{"groups": ["Team X", "Team Y"]}'
spec:
  ingressClassName: nginx
  rules:
  - host: demo.mydomain.com
    http:
      paths:
      - path: /foo/admin
        pathType: Prefix
        backend:
          service:
            name: demo-project
            port:
              number: 8080
```
 
 So I think the problem is only related to Regex paths in combination with others for the same host ..
