### ISSUE TITLE
Wrong certificate exposed

### ISSUE THREAD

**Issue by rguichard** [pomerium/ingress-controller#142]
## What happened?

An Ingress (with Pomerium Ingress Controller) exposes the authenticate Service with a cert-manager-generated certificate but this certificate is not provided to the http client. Instead a self signed certificate (used for communication between Pomerium component) is provided. As if it was a TLS passthrough, the Ingress doesn't terminate the TLS communication.

If I change the ingressClass of the Ingress (for traefik for example), the correct certificate is exposed.

## What did you expect to happen?

The certificate defined in the Ingress resource should be exposed.

## How'd it happen?

- deploy an Ingress with Pomerium Ingress Controller and authenticate Service as upstream application.
- curl the ingress
- get a TLS error (self signed certificate)

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): `0.16.2`
- Pomerium Helm chart : `29.0.1`
- Server Operating System/Architecture/Cloud: AWS EKS

## What's your values.yaml

```
pomerium:
  config:
    rootDomain: domain.com
    policy: []
  authenticate:
    replicaCount: 3
    ingress:
      tls:
        secretName: pomerium-authenticate-cert
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-dns
    idp: {}
  proxy:
    replicaCount: 3
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "external"
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
        service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: "deregistration_delay.timeout_seconds=60,stickiness.enabled=false"
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "10"
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
        service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "false"
  ingressController:
    replicaCount: 3
    enabled: true
    config:
      ingressClass: pomerium.io/ingress-controller-external
    ingressClassResource:
      enabled: true
      name: pomerium-external
      controllerName: pomerium.io/ingress-controller-external
  metrics:
    enabled: true
```

## What did you see in the logs?

It generates this Ingress :
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    ingress.pomerium.io/allow_public_unauthenticated_access: "true"
    ingress.pomerium.io/preserve_host_header: "true"
    ingress.pomerium.io/secure_upstream: "true"
    ingress.pomerium.io/tls_server_name: authenticate.domain.com
    ingress.pomerium.io/secure_upstream: "true"
  labels:
    app.kubernetes.io/instance: pomerium
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pomerium
    helm.sh/chart: pomerium-29.0.1
    oi/appname: pomerium-external-kube-shared-nonprod
  name: pomerium-authenticate
  namespace: pomerium-external
spec:
  ingressClassName: pomerium-external
  rules:
  - host: authenticate.domain.com
    http:
      paths:
      - backend:
          service:
            name: pomerium-authenticate
            port:
              name: https
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - authenticate.domain.com
    secretName: pomerium-authenticate-cert
```

**Comment by travisgroth** [comment]
@rguichard can you provide the logs from the ingress controller when it processes that Ingress resource?

**Comment by rguichard** [comment]
Ingress controller 
```
{"level":"info","ts":1644879449.631355,"logger":"controller.ingress","msg":"new pomerium config applied","reconciler group":"networking.k8s.io","reconciler kind":"Ingress","name":"pomerium-authenticate","namespace":"pomerium-external"
```

Pomerium proxy when I curl, sometimes I get 503, sometimes 302 to my IdP.
```
{"level":"info","service":"envoy","upstream-cluster":"pomerium-external-pomerium-authenticate-authenticate-shared-dev4apps-com-6ceaeb9bf3be8e62","method":"GET","authority":"authenticate.shared.dev4apps.com","path":"/.pomerium","user-agent":"curl/7.74.0","referer":"","forwarded-for":"172.30.81.217","request-id":"17e3fc3d-aecb-4137-8c66-65a2f8fc4b33","duration":1.540371,"size":91,"response-code":503,"response-code-details":"upstream_reset_before_response_started{connection_failure}","time":"2022-02-14T23:17:25Z","message":"http-request"}
{"level":"info","service":"envoy","upstream-cluster":"pomerium-external-pomerium-authenticate-authenticate-shared-dev4apps-com-6ceaeb9bf3be8e62","method":"GET","authority":"authenticate.shared.dev4apps.com","path":"/.pomerium","user-agent":"curl/7.74.0","referer":"","forwarded-for":"172.30.81.217","request-id":"abefec8f-4cc1-4014-9a89-373ae33af752","duration":106.438187,"size":612,"response-code":302,"response-code-details":"via_upstream","time":"2022-02-14T23:17:27Z","message":"http-request"}
```

**Comment by travisgroth** [comment]
I'm not able to reproduce this.  There are some minor tweaks to your original config but they should not be material in which certificate is served.  There's no reference to `pomerium-tls` in any resources that I can find.

1. Set up a self signed CA issuer per https://cert-manager.io/docs/tutorials/acme/pomerium-ingress/#configure-a-private-certificate-issuer
2. config:

```yaml
config:
  rootDomain: localhost.pomerium.io
  policy: []
authenticate:
  replicaCount: 1 # changed
  ingress:
    tls:
      secretName: pomerium-authenticate-cert
    annotations:
      cert-manager.io/issuer: pomerium-issuer # use a self signed issuer to avoid needing a reachable LoadBalancer service
      ingress.pomerium.io/tls_skip_verify: "true" # due to using a self signed issuer rather than let's encrypt
  idp: {}
proxy:
  replicaCount: 1 # changed
ingressController:
  enabled: true
  config:
    ingressClass: pomerium.io/ingress-controller-external
  ingressClassResource:
    enabled: true
    name: pomerium-external
    controllerName: pomerium.io/ingress-controller-external
metrics:
  enabled: true
```

3. I have no `pomerium-tls` secret.  The values you have there would not use it since they do not specify an existingSecret or disable certificate generation.

```shell
% k get certificate
NAME                         READY   SECRET                       AGE
pomerium-authenticate-cert   True    pomerium-authenticate-cert   7m35s
pomerium-ca                  True    pomerium-ca                  30m

% kubectl get secret pomerium-authenticate-cert -o json | jq '.data."tls.crt"' -r | base64 -d | openssl x509 -text | md5sum
758366ffeb27d0c130982370e7fcbd05  -

% openssl s_client -connect authenticate.localhost.pomerium.io:443 | openssl x509 -text | md5sum
758366ffeb27d0c130982370e7fcbd05  -
```

4. I add a self signed cert to the cluster (without referencing it) copied from [here](https://cert-manager.io/docs/tutorials/acme/pomerium-ingress/#install-the-pomerium-ingress-controller):

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pomerium-cert
  namespace: pomerium
spec:
  secretName: pomerium-tls
  issuerRef:
    name: pomerium-issuer
    kind: Issuer
  usages:
    - server auth
    - client auth
  dnsNames:
    - pomerium-proxy.pomerium.svc.cluster.local
    - pomerium-authorize.pomerium.svc.cluster.local
    - pomerium-databroker.pomerium.svc.cluster.local
    - pomerium-authenticate.pomerium.svc.cluster.local
 ```

```bash
% k get cert
NAME                         READY   SECRET                       AGE
pomerium-authenticate-cert   True    pomerium-authenticate-cert   10m
pomerium-ca                  True    pomerium-ca                  32m
pomerium-cert                True    pomerium-tls                 3s
```

5.  I still get the correct cert:

```bash
openssl s_client -connect authenticate.localhost.pomerium.io:443 | openssl x509 -text | md5sum
758366ffeb27d0c130982370e7fcbd05  -
```

I'm not sure how to explain the behavior you're seeing but it appears to be specific to your environment, somehow.

**Comment by travisgroth** [comment]
Closing for now, pending more info on reproduction.

**Comment by boskisam** [comment]
Hi, @travisgroth i am experiencing a similar issue. 
In my case i use auto-generated certs for comms between services. In my case i use manually-generated letsencrypt certs.
just installed pomerium helm-chart version 31.0.1 hoping my problems with 421 are fixed, but no luck.
values for helm-chart:
```yaml
config:
  sharedSecret: <redacted> # You can use "head -c32 /dev/urandom | base64" to generate.
  cookieSecret: <redacted> # You can use "head -c32 /dev/urandom | base64" to generate.
  rootDomain: example.com
  generateTLS: true # On by default, disabled when cert-manager or another solution is in place.
authenticate:
  existingExternalTLSSecret: authenticate-ingress-tls
  idp:
    provider: oidc
    clientID: pomerium
    clientSecret: pomerium
    serviceAccount: <redacted>
    url: <redacted>
    scopes:  openid,profile,email,phone,roles
  ingress:
    tls:
      secretName: authenticate-ingress-tls
resources:
  limits:
    cpu: 1
    memory: 600Mi
  requests:
    cpu: 100m
    memory: 300Mi
ingressController:
  enabled: true
proxy:
  existingTLSSecret: examplecom-wildcard-cert
  service:
    type: LoadBalancer
ingress:
  enabled: false
```
ingress resource generated by helm installation (get ingress -o yaml), getting it here as an example, all other apps on pomerium ingress behave the same.
```yaml
apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      field.cattle.io/publicEndpoints: '[{"addresses":["<redacted>"],"port":443,"protocol":"HTTPS","serviceName":"pomerium:pomerium-authenticate","ingressName":"pomerium:pomerium-authenticate","hostname":"authenticate.example.com","path":"/","allNodes":false}]'
      ingress.pomerium.io/allow_public_unauthenticated_access: "true"
      ingress.pomerium.io/secure_upstream: "true"
      meta.helm.sh/release-name: pomerium
      meta.helm.sh/release-namespace: pomerium
    creationTimestamp: "2021-11-12T14:40:05Z"
    generation: 3
    labels:
      app.kubernetes.io/instance: pomerium
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: pomerium
      helm.sh/chart: pomerium-31.0.1
    name: pomerium-authenticate
    namespace: pomerium
    resourceVersion: "103810960"
    uid: <redacted>
  spec:
    ingressClassName: pomerium
    rules:
    - host: authenticate.example.com
      http:
        paths:
        - backend:
            service:
              name: pomerium-authenticate
              port:
                name: https
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - authenticate.example.com
      secretName: authenticate-ingress-tls
  status:
    loadBalancer:
      ingress:
      - ip: <redacted>
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

Where both _**authenticate-ingress-tls**_ and _**examplecom-wildcard-cert**_ are located in pomerium namespace.
- authenticate-ingress-tls with cert for authenticate.example.com
- examplecom-wildcard-cert with cert for *.example.com and example.com

Whenever i access authenticate.example.com (or any other domain specified in ingress resources) i am served with the wildcard certificate. 
If i unset proxy.existingTLSSecret in values i get served with auto-generated certificate which is rejected by my browser. - this makes me think i (almost) always am served with proxy certificate. 

I encountered this problem when our testers wanted to access secured endpoints on safari. (i am trying to solve this problem https://github.com/pomerium/pomerium/issues/2150)

**Comment by boskisam** [comment]
@travisgroth can we reopen the issue?

**Comment by boskisam** [comment]
@travisgroth pinging again. Is the info I provided enough to start some investigation?

**Comment by desimone** [comment]
Possibly Related (and closed by) https://github.com/pomerium/pomerium/pull/3596

History:
- https://github.com/pomerium/pomerium/issues/2150
- https://github.com/pomerium/pomerium/pull/3596
- https://github.com/pomerium/internal/issues/972

**Comment by wasaga** [comment]
You need create a certificate for the authenticate endpoint.

Assuming the following: 
- you are using `cert-manager` to manage certificates in your cluster,
- you have a `letsencrypt-prod` `ClusterIssuer`
- your authenticate endpoint is `authenticate.corp.com` 
- you deployed pomerium using new recommended manifests + CRD method 

Certificate spec: 

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pomerium-authenticate-tls
  namespace: pomerium
spec:
  dnsNames:
  - authenticate.corp.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: pomerium-authenticate-tls
  usages:
  - digital signature
  - key encipherment
```

the following should be added into your `pomerium/global` CRD:

```yaml
apiVersion: ingress.pomerium.io/v1
kind: Pomerium
metadata:
  name: global
spec:
  authenticate:
    url: https://authenticate.corp.com
  certificates:
  - pomerium/pomerium-authenticate-tls
```
