### ISSUE TITLE
do not require TLS cert for HTTP01 solvers

### ISSUE THREAD

**Issue by wasaga** [pomerium/ingress-controller#193]
## What happened?

Apparently HTTP01 solver was broken when we enforced TLS certs for the ingress. 

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: pomerium
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0,::/0
  generateName: cm-acme-http-solver-
  generation: 1
  labels:
    acme.cert-manager.io/http-domain: [redacted]
    acme.cert-manager.io/http-token: [redacted]
    acme.cert-manager.io/http01-solver: "true"
  name: cm-acme-http-solver-sffdb
  namespace: pomerium
  ownerReferences:
  - apiVersion: acme.cert-manager.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Challenge
    name: authenticate[redacted]
spec:
  rules:
  - host: [redacted]
    http:
      paths:
      - backend:
          service:
            name: cm-acme-http-solver-wpsmt
            port:
              number: 8089
        path: /.well-known/acme-challenge/[redacted]
        pathType: ImplementationSpecific

```

```
fetch ingress related resources: tls: spec.TLS.secretName was empty, could not get default cert from ingressClass: default cert secret name: annotation ingress.pomerium.io/default-cert-secret is missing
```

## How'd it happen?

1. define HTTP01 issuer
2. request new certificate

## What's your environment like?

Pomerium Ingress 0.17.0 

## What did you see in the logs?

```logs
fetch ingress related resources: tls: spec.TLS.secretName was empty, could not get default cert from ingressClass: default cert secret name: annotation ingress.pomerium.io/default-cert-secret is missing
```
