### ISSUE TITLE
How to add Certificate Authority (OIDC x509: certificate signed by unknown authority)

### ISSUE THREAD

**Issue by Benjvfr** [pomerium/ingress-controller#476]
Hello,

How to add a certificate authority in case of Pomerium Ingress Controller for OIDC ? 

I have a Keycloak instance with certificate signed by our internal CA, and I naturally have a 500 Internal Error when trying to browse authenticate.mydomain.org :

```sh
"error":"failed to get sign in url: identity/oidc: could not connect to oidc: Get \"https://id.mydomain.org/realms/xxx/.well-known/openid-configuration\": x509: certificate signed by unknown authority","status":500,"status-text":"Internal Server Error","request-id":"b932c32b-2f33-44f1-bfb0-a843932db7d6","time":"2023-01-09T09:47:37Z","message":"httputil: error"}
```

I tried to add the Certificate Authority variable "CERTIFICATE_AUTHORITY" in the deployment, but it seems not the right way to do it. Here is my file "patch-deployment.yaml" :

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomerium
  namespace: pomerium
spec:
  template:
    spec:
      containers:
        - name: pomerium
          env:
            - name: CERTIFICATE_AUTHORITY
              value: <base64-encoded-pem>
```
When I connect inside the pod, I can see the variable injected.

Am I missing something or there is no way to add a CA to Pomerium Ingress in Kubernetes ? I don't see an option to add it in the Pomerium CRD for the global config.
