### ISSUE TITLE
503 error between pomerium and upstream

### ISSUE THREAD

**Issue by max-l-f** [pomerium/ingress-controller#585]
## What happened?
An Ingress (with Pomerium Ingress Controller) exposes the authenticate Service with a wildcard cert-manager-generated certificate.

The configuration works for other services without any issues.

Use case: expose the spark driver ui through an ingress resource created by the spark operator.
The spark driver exposes several ports with two different services:
- service-1 ports:
```yaml
ports:
  - name: spark-driver-ui-port
    port: 4040
    protocol: TCP
    targetPort: 4040
```
- service-2 ports:
```yaml
ports:
  - name: driver-rpc-port
    port: 7078
    protocol: TCP
    targetPort: 7078
  - name: blockmanager
    port: 7079
    protocol: TCP
    targetPort: 7079
  - name: spark-ui
    port: 4040
    protocol: TCP
    targetPort: 4040
```

The ingress created by the spark-operator is similar to the following:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.pomerium.io/allow_any_authenticated_user: "true"
    ingress.pomerium.io/pass_identity_headers: "true"
  name: spark-app-ingress
spec:
  ingressClassName: pomerium
  rules:
    - host: app-namespace.sparkui.thierry.michel.bob.toto.example
      http:
        paths:
          - backend:
              service:
                name: service-1
                port:
                  number: 4040
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - sparkui.thierry.michel.bob.toto.example
      secretName: sparkui-wildcard-tls
```

result:

white page with this error: `upstream connect error or disconnect/reset before headers. reset reason: connection failure`

If I change the ingressClass of the Ingress (for nginx for example), it works

The ingress resource gets created before the upstream services/pods 

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): 0.21.2
- Server Operating System/Architecture/Cloud: Kubernetes 1.23

args in the deployment:

```yaml
          args:
            - all-in-one
            - --pomerium-config=global
            - --update-status-from-service=$(POMERIUM_NAMESPACE)/pomerium-proxy
            - --metrics-bind-address=$(POD_IP):9090
```

pomerium crd:

```yaml
apiVersion: ingress.pomerium.io/v1
kind: Pomerium
metadata:
  annotations:
    meta.helm.sh/release-name: pomerium
    meta.helm.sh/release-namespace: pomerium
  labels:
    app.kubernetes.io/instance: pomerium
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/version: 0.21.2
    helm.sh/chart: pomerium-1.0.3
  name: global
spec:
  authenticate:
    url: https://auth.thierry.michel.bob.toto.example
  certificates:
  - pomerium/pomerium-tls
  identityProvider:
    provider: oidc
    scopes:
    - openid
    - profile
    - email
    - groups
    secret: pomerium/pomerium-idp
    url: https://auth.tata
  jwtClaimHeaders:
    X-cuid: sub
    X-email: email
    X-groups: groups
    x-auth-request-email: sub
  secrets: pomerium/bootstrap
```

## What did you see in the logs?

```logs
{"level":"info","service":"authorize","request-id":"7fcdf6a1-0cc4-46f9-9e78-51bc999e7b61","check-request-id":"7fcdf6a1-0cc4-46f9-9e78-51bc999e7b61","method":"GET","path":"/favicon.ico","host":"app-namespace.sparkui.thierry.michel.bob.toto.example","query":"","ip":"192.168.128.0","session-id":"b22d7c45-347c-4cf7-bb31-30db7281c53d","allow":true,"allow-why-true":["user-ok"],"deny":false,"deny-why-false":["valid-client-certificate-or-none-required"],"user":"abcdefgh","email":"toto@example.com","time":"2023-04-06T16:15:12Z","message":"authorize check"}
{"level":"info","service":"envoy","upstream-cluster":"service-1-705797282278bca3","method":"GET","authority":"app-namespace.sparkui.thierry.michel.bob.toto.example","path":"/","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0","referer":"","forwarded-for":"192.168.129.0","request-id":"a684c332-f40f-4f7c-8301-029bfc3aaf56","duration":10010.911458,"size":91,"response-code":503,"response-code-details":"upstream_reset_before_response_started{connection_failure}","time":"2023-04-06T16:15:12Z","message":"http-request"}
```
