### ISSUE TITLE
More Complicated Example than what is provided in Documentation

### ISSUE THREAD

**Issue by dmaljovec** [pomerium/ingress-controller#711]
**Is your feature request related to a problem? Please describe.**

We are trying to protect a service deployed into a kubernetes cluster, let's call it `blueberry`, by ensuring that only a select set of users that have a group claim of `blueberry_users` coming from an IdP can access the API. Furthermore, there is a select set of endpoints behind an `/admin` path that we further want to restrict to only a `blueberry_admins` claim. We are able to accomplish this by using two ingress objects that look something like the following:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.pomerium.io/pass_identity_headers: 'true'
    ingress.pomerium.io/policy: |
      allow:
        and:
          - claim/groups: 'blueberry_users'
  labels:
    app: blueberry
  name: blueberry-split-common
  namespace: blueberry
spec:
  ingressClassName: pomerium
  rules:
    - host: blueberry.someplace-nice.io
      http:
        paths:
          - backend:
              service:
                name: blueberry
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - blueberry.someplace-nice.io
      secretName: blueberry-common-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.pomerium.io/pass_identity_headers: 'true'
    ingress.pomerium.io/policy: |
      allow:
        and:
          - claim/groups: 'blueberry_admins'
  labels:
    app: blueberry
  name: blueberry-split-admin
  namespace: blueberry
spec:
  ingressClassName: pomerium
  rules:
    - host: blueberry.someplace-nice.io
      http:
        paths:
          - backend:
              service:
                name: blueberry
                port:
                  number: 80
            path: /admin
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - blueberry.someplace-nice.io
      secretName:blueberry-admin-tls
```

**Describe the solution you'd like**

Either:
 - More examples demonstrating more complicated patterns of using Pomerium Policy Language inside ingress objects
 - An explanation in the docs as to why using multiple ingresses like the example above _should_ be the preferred path
 - An improvement to policy language such that we can do `not` operators like the following to accomplish this without needing a second ingress object:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.pomerium.io/pass_identity_headers: 'true'
    ingress.pomerium.io/path_regex: 'true'
    ingress.pomerium.io/policy: |
      allow:
        or:
          - claim/groups: 'blueberry_users'
          - claim/groups: 'blueberry_admins'
      deny:
        and:
          - http_path:
              contains: "/admin"
          - claim/groups: 
              not:
                is: 'blueberry_admins'
  labels:
    app: blueberry
  name: blueberry-combined
  namespace: blueberry
spec:
  ingressClassName: pomerium
  rules:
    - host: blueberry.someplace-nice.io
      http:
        paths:
          - backend:
              service:
                name: blueberry
                port:
                  number: 80
            path: /(.*)$
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - blueberry.someplace-nice.io
      secretName: blueberry-combined.prod.rxrx.io-tls
```

**Describe alternatives you've considered**

As stated above, we are able to accomplish what we want using multiple ingress objects, but we feel this is excessive for our modest policy.

**Explain any additional use-cases**

Having more examples of different kinds of use cases in the docs or in the repo itself could provide some fodder for us to think more creatively on the matter. We are currently trying to understand what "Anything" means in the context of data formats for criteria in the [Pomerium Policy Language docs](https://www.pomerium.com/docs/capabilities/ppl#criteria), and we would also like to understand better where we can nest logical operators. Either the spec is limited to the simple use cases in the docs or we are not able to fully leverage the spec because of lack of inspirational examples.

**Additional context**

Thank you for the product, and if there is any way we can contribute or provide more information, please let us know!

cc: @ninetyninenines @pineappleEnthusiast @squeezboks
