### ISSUE TITLE
Rewriting Redirects

### ISSUE THREAD

**Issue by denniskniep** [pomerium/ingress-controller#875]
**Is your feature request related to a problem? Please describe.**
A website (upstream) is doing a redirect and envoy is not rewriting the host-part of the location header in the response.

The redirect is happening at the root url and redirecting to the same url + a subpath 

i.e.
`foo.pomerium.io` points to `foo.com`
(configured like this example https://docs.pomerium.com/docs/deploy/k8s/ingress#external-services) 

Requesting `foo.pomerium.io`  returns a `302 `with `Location: foo.com/sub/path`
Therefore Browser is following that location header and tries to open ` foo.com/sub/path`

But what I expect is that envoy rewrites the `Location: foo.com/sub/path` to `Location: foo.pomerium.io/sub/path`
and Browser will open `foo.pomerium.io/sub/path`

**Comment by wasaga** [comment]
should be achievable by adding https://www.pomerium.com/docs/reference/routes/headers#rewrite-response-headers to your route

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.pomerium.io/rewrite_response_headers: |
      - header: Location
        prefix: http://foo.com/sub/path
        value: https://foo.pomerium.io/sub/path
```
