### ISSUE TITLE
Reconsider deprecating the operator

### ISSUE THREAD

**Issue by xeor** [pomerium/ingress-controller#89]
**Is your feature request related to a problem? Please describe.**

Deprecating of the operator

**Describe the solution you'd like**

I see why the ingress-controller seams like a more logical solution, but deprecating the operator will break a lot of workflows!

**Describe alternatives you've considered**

Not using pomerium anymore :(

**Explain any additional use-cases**

I use the operator with the nginx-ingress controller. Replacing that with another ingress-controller would mean that:

* There is no way to use nginx-controller functionality anymore, example, `use-geoip2`, `custom-http-errors`, `ssl-dh-param` and a [ton](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/) of other advanced options.
* I was using annotations like `nginx.ingress.kubernetes.io/auth-snippet` to further decide when I wanted pomerium to do authentication.

There are also other purpose built ingress controllers that will loose similar functionality, or even worse.

**Suggestion**

I totally see why you want to create an ingress-controller instead of an operator. But they have separate use-cases, even tho they share some of the same functionality.

What about creating a shared lib between them instead, then have both?

Please don't reinvent all the ingress-controllers out there, but have it as an option for those who just want something simple.

**Comment by travisgroth** [comment]
Hi @xeor - we appreciate the enthusiasm.

Fortunately, there's an option to run the ingress controller in an operator-compatible way and we don't plan on removing that.  99% of the logic is identical so the overhead of two projects to differentiate the behavior wasn't worth doing.

As mentioned in the [deprecation notice](https://github.com/pomerium/pomerium-operator#warning-deprecation-notice), the helm chart has an [option](https://github.com/pomerium/pomerium-helm/tree/master/charts/pomerium#2500-1) to run as we did previously.

Internally, the difference is simply whether we assert ownership of an `Ingress` and maintain the status field or not.  This is controlled with a runtime flag.

If there's something else missing for your use case please do open a feature request outlining it.

**Comment by xeor** [comment]
Thanks for the answer! I'm very happy that there still is a solution :)

I was getting
`{"level":"info","ts":1636847221.7454927,"logger":"controller.ingress","msg":"deleted from pomerium","reconciler group":"networking.k8s.io","reconciler kind":"Ingress","name":"http1-http","namespace":"default","reason":"not marked to be managed by this controller"}` after following the procedure of upgrading.

I tried many configurations playing with `ingressClass` and I have nginx as an `ingressClass` object as well.

```
ingressController:
  enabled: true
  # This is in the doc, but not used in helm templates
  # ingressClass: nginx
  config:
    operatorMode: true
    # This is used, but isnt the ingressClass name, it is the CONTROLLER name, like k8s.io/ingress-nginx "kubectl get ingressclass"
    ingressClass: nginx

ingress:
  annotations:
    # Not sure why, but I need this as well..
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
```

Gotten a little longer, but I still have issues with "just migrating over", not sure if it's a new bug or not, but now I'm getting `{"level":"error","ts":1636848241.426951,"logger":"controller.ingress","msg":"obtaining ingress related resources","reconciler group":"networking.k8s.io","reconciler kind":"Ingress","name":"http1-http","namespace":"default","deps":[{"Kind":"Secret","Namespace":"default","Name":""}],"error":"tls: get secret default/: Secret \"\" not found"}` in the ingress-controller when it sees a new resource it should make a rule for.
