### ISSUE TITLE
FEAT: Supporting non-standard ports

### ISSUE THREAD

**Issue by venkatamutyala** [pomerium/ingress-controller#926]
**Is your feature request related to a problem? Please describe.**

Yes.

A clear and concise description of what the problem is. 

It seems like pomerium can only support standard ports 80 and 443. If i do example.com:8443 it'll give me a 404.

**Describe the solution you'd like**

I'd like to be able to specify 8443 or another non-standard port

**Describe alternatives you've considered**

This works in curl but i don't think i can easily recreate this in a popular browser (ex. chrome):

```
curl --header 'Host: example.com' https://example.com:9096
```

**Explain any additional use-cases**

I'd like to keep port 80/443 for apps that use ingress-nginx ingress controller and i'd like to avoid having to get a second ipv4 address just to use pomerium

**Additional context**
Related: 
- https://github.com/pomerium/pomerium/issues/3808
- https://github.com/pomerium/pomerium/issues/959

**Comment by calebdoxsey** [comment]
I have moved this issue to the ingress controller repository.

**Comment by venkatamutyala** [comment]
Thanks.

**Comment by calebdoxsey** [comment]
Related: https://github.com/pomerium/pomerium/issues/4460

Adding an option to ignore the port for matching would fix this issue as well.

**Comment by kenjenkins** [comment]
Yes, let's investigate the feasibility of adding a config option to ignore the port.

**Comment by calebdoxsey** [comment]
This has been implemented. Using an ingress rule like:

```yaml
spec:
  ingressClassName: pomerium
  rules:
    - host: "verify.EXAMPLE.com"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: verify
                port:
                  number: 8000
```

And running a `NodePort` service on `:30443` the request is routed properly.
