### ISSUE TITLE
ingress.pomerium.io/allowed_idp_claims doesn't work anymore

### ISSUE THREAD

**Issue by sherifkayad** [pomerium/ingress-controller#94]
## What happened?
We were heavy users of the Pomerium Operator until it got deprecated in favor of the Ingress Controller. Everything was working smoothly and now we wanted to migrate to the Ingress Controller.

We have a setup consisting of Nginx as the main Ingress Controller and honestly we don't want to change that! .. So we used the Forward Auth mechanism and we want to keep using it.

Among the used annotations we have on the Nginx Ingress objects is the following:
```yaml
ingress.pomerium.io/allowed_idp_claims: '"groups": ["Team X", "Team Y"]'
```
That basically instructed Pomerium to allow any members of the groups `Team X` or `Team Y`. The Ingress controller is refusing that annotation with the message below:
```
{"level":"error","ts":1638349309.9580674,"logger":"controller.ingress","msg":"Reconciler error","reconciler group":"networking.k8s.io","reconciler kind":"Ingress","name":"my-secure-ingress","namespace":"my-namespace","error":"upsert: upsert routes: parsing ingress: annotations: applying policy annotations: yaml: mapping values are not allowed in this context"}
```

## What did you expect to happen?
The allowed IDP Claims e.g. to fetch groups mapping should work as expected (as per the Operator)

## How'd it happen?
Refer to the the `What Happened` section above

## What's your environment like?

- Pomerium versions:
-- Helm version 25.0.3
-- Pomerium version 0.15.7
-- Pomerium Ingress Controller version 0.15.2
- Server Operating System/Architecture/Cloud:
-- AWS EKS v1.21
-- Helm 3

## What's your config.yaml?

```config.yaml
autocert: false
dns_lookup_family: V4_ONLY
address: :80
grpc_address: :80
authenticate_service_url: https://pomerium.mydomain.com
authorize_service_url: http://pomerium-authorize.pomerium.svc.cluster.local
databroker_service_url: http://pomerium-databroker.pomerium.svc.cluster.local
idp_provider: oidc
idp_scopes: [openid profile email groups offline_access]
idp_provider_url: https://myidp.com
insecure_server: true
grpc_insecure: true

cookie_domain: mydomain.com
databroker_storage_connection_string: rediss://:password@amazon.elasticache.endpoint.com
databroker_storage_tls_skip_verify: true
databroker_storage_type: redis
forward_auth_url: https://forwardauth.mydomain.com
cookie_secret: secret
shared_secret: secret2
idp_client_id: secret3
idp_client_secret: secret4
idp_service_account: pomerium-authenticate
databroker_storage_tls_skip_verify: true    
routes:
  - allow_any_authenticated_user: true
    allow_spdy: true
    allow_websockets: true
    from: https://dashboard.mydomain.com
    kubernetes_service_account_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    to: http://kubernetes-dashboard.kube-system.svc:443
  - allow_any_authenticated_user: true
    allow_spdy: true
    allow_websockets: true
    from: https://kubernetes.mydomain.com
    kubernetes_service_account_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    tls_skip_verify: true
    to: https://kubernetes.default.svc
```

## What did you see in the logs?

```logs
{"level":"error","ts":1638349309.9580674,"logger":"controller.ingress","msg":"Reconciler error","reconciler group":"networking.k8s.io","reconciler kind":"Ingress","name":"my-secure-ingress","namespace":"my-namespace","error":"upsert: upsert routes: parsing ingress: annotations: applying policy annotations: yaml: mapping values are not allowed in this context"}
```

## Additional context

My ingress definition:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-secure-ingress
  namespace: my-namespace
  labels:
    app: demo
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: "https://forwardauth.mydomain.com/?uri=https://$host$request_uri"
    nginx.ingress.kubernetes.io/auth-url: "https://forwardauth.mydomain.com/verify?uri=https://$host$request_uri"
    ingress.pomerium.io/allowed_idp_claims: '"groups": ["Team X", "Team Y"]'
spec:
  ingressClassName: nginx
  rules:
  - host: demo.mydomain.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: demo
            port:
              number: 8080
```

**Comment by sherifkayad** [comment]
@travisgroth an update here:
After some digging in the Controller code base, I found out that the probable right syntax is as follows:
```yaml
ingress.pomerium.io/allowed_idp_claims: '{"groups": ["Team X", "Team Y"]}'
```

With the allowed IDP Claims as a JSON Object the controller admits that and doesn't complain. However, the problem now is that users of either group won't be authorized! .. There's definitely something wrong here

**Comment by sherifkayad** [comment]
Another update:
Actually the simplest annotation `ingress.pomerium.io/allow_any_authenticated_user: "true"` doesn't work for me. I keep getting the infinite redirect loop indicating that it's not working.

My Ingress is as follows:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-secure-ingress
  namespace: my-namespace
  labels:
    app: demo
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: "https://forwardauth.mydomain.com/?uri=https://$host$request_uri"
    nginx.ingress.kubernetes.io/auth-url: "https://forwardauth.mydomain.com/verify?uri=https://$host$request_uri"
    ingress.pomerium.io/allow_any_authenticated_user: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: demo.mydomain.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: demo
            port:
              number: 8080
```
