### ISSUE TITLE
Support for wildcard / catch-all host

### ISSUE THREAD

**Issue by bennesp** [pomerium/ingress-controller#941]
## What happened?

Not writing any `host` in the `Ingress` resource results into `pomerium` not accepting the `Ingress` because:

> {"level":"error","ts":"2024-04-22T08:58:44Z","logger":"pomerium-ingress","msg":"not reconciled","controller":"pomerium-ingress","controllerGroup":"networking.k8s.io","controllerKind":"Ingress","Ingress":{"name":"test","namespace":"test"},"namespace":"test","name":"test","reconcileID":"715a9096-eda6-41c1-97d9-832f85f76076","ingress":"test/test","error":"**parsing ingress: host is required**"}

## What did you expect to happen?

Ingress specification allows to avoid specifying the `host` field, since it's optional.

> When no host is specified, the rule applies to all inbound HTTP traffic through the IP address specified. ([Source](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules))

Since Pomerium supports wildcard (https://github.com/pomerium/pomerium/pull/4131) the ingress controller should be able to map the absence of the `host` field to a `*` host.

It cannot be manually done because the `host` inside `Ingress`, if provided, must conform to a regex that do not allow to use just `*`: `\*\.[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*`

![Screenshot 2024-04-22 alle 11 15 51](https://github.com/pomerium/ingress-controller/assets/5445545/e56b8e31-2613-4465-998a-92f96f8bdc07)

## How'd it happen?

Create a simple Ingress with no host:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
  namespace: test
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test
                port:
                  number: 80
```

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): v0.25.1
- Server Operating System/Architecture/Cloud: Kubernetes

## What's your config.yaml?

```config.yaml
apiVersion: ingress.pomerium.io/v1
kind: Pomerium
metadata:
  name: global
spec:
  authenticate:
    url: https://example.com
  cookie:
    domain: example.com
  identityProvider:
    provider: auth0
    secret: pomerium/idp-auth0
    url: https://example.auth0.com
  secrets: pomerium/bootstrap
  storage:
    postgres:
      secret: pomerium/db-connection
```
