### ISSUE TITLE
Parsing ingress: annotations: proto: invalid google.protobuf.Duration value

### ISSUE THREAD

**Issue by bennesp** [pomerium/ingress-controller#981]
## What happened?

I am receiving the following event on the Ingress:

```
parsing ingress: annotations: proto: (line 1:83): invalid google.protobuf.Duration value "2m"
```

## What did you expect to happen?

I expected to be able to use "2m" as in "2 minutes" in the annotation `ingress.pomerium.io/timeout` [documented here](https://www.pomerium.com/docs/reference/routes/timeouts#route-timeout)

## How'd it happen?

1. Create an ingress with annotation `ingress.pomerium.io/timeout: '2m'`
2. Look at pomerium logs or at the ingress' events

## What's your environment like?

- Pomerium version: `docker.io/pomerium/ingress-controller@sha256:f40d7bfeb618f39c9f8190dc21cfc6f53eb046257b1eda848c3585bc6a206e69` (friendly name: `docker.io/pomerium/ingress-controller:v0.26.0`)
- Server Operating System/Architecture/Cloud: EKS

## What's your config.yaml?

Configuration is applied using custom resource `Pomerium`

```yaml
apiVersion: ingress.pomerium.io/v1
kind: Pomerium
metadata:
  name: global
  namespace: pomerium
spec:
  authenticate:
    url: https://REDACTED
  certificates:
    - pomerium/default-tls
  cookie:
    domain: REDACTED
    expire: 4h
  identityProvider:
    provider: auth0
    secret: pomerium/idp-auth0
    url: https://REDACTED.auth0.com
  secrets: pomerium/bootstrap
  storage:
    postgres:
      secret: pomerium/db-connection
  timeouts:
    read: 2m
```

## What did you see in the logs?

```logs
{"level":"error","ts":"2024-06-17T14:21:22Z","logger":"pomerium-ingress","msg":"not reconciled","controller":"pomerium-ingress","controllerGroup":"networking.k8s.io","controllerKind":"Ingress","Ingress":{"name":"pomerium","namespace":"default"},"namespace":"default","name":"pomerium","reconcileID":"ae8b4864-ec60-4a50-9dfd-d50f0b6a45ee","ingress":"default/pomerium","error":"parsing ingress: annotations: proto: (line 1:83): invalid google.protobuf.Duration value \"2m\""}
```

## Additional context

Using `120s` is a valid workaround. However, in the documentation is stated that "2m" should work (See the example given in [Idle Timeout](https://www.pomerium.com/docs/reference/routes/timeouts#idle-timeout) that references to the non-idle timeout)
